apiVersion: v1
kind: Secret
metadata:
  name: chaos-messenger-secret
  namespace: chaos-messenger
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_32_CHAR_MIN_LENGTH_12345678"
  VAPID_PRIVATE_KEY: ""
