ALTER TABLE chat_participants
    ADD COLUMN IF NOT EXISTS muted_until TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS banned_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS banned_by BIGINT NULL,
    ADD COLUMN IF NOT EXISTS ban_reason VARCHAR(255) NULL;
