-- HASH-partition message_envelopes by chat_id so inserts and per-chat reads
-- do not pile onto a single heap. PostgreSQL requires the partition key in
-- every unique constraint, so uniqueness becomes (chat_id, message_id, target_device_id).

ALTER TABLE message_envelopes RENAME TO message_envelopes_legacy;
ALTER SEQUENCE IF EXISTS message_envelopes_id_seq RENAME TO message_envelopes_legacy_id_seq;

DO $$
DECLARE
    rec record;
BEGIN
    FOR rec IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'message_envelopes_legacy'::regclass
    LOOP
        EXECUTE format('ALTER TABLE message_envelopes_legacy DROP CONSTRAINT IF EXISTS %I', rec.conname);
    END LOOP;
END $$;

DROP INDEX IF EXISTS idx_message_envelopes_message_id;
DROP INDEX IF EXISTS idx_message_envelopes_chat_target_device;
DROP INDEX IF EXISTS idx_message_envelopes_target_device_db_id;

CREATE TABLE message_envelopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    target_device_db_id BIGINT NOT NULL,
    target_device_id VARCHAR(100) NOT NULL,
    sender_user_id BIGINT NOT NULL,
    sender_device_id VARCHAR(100) NOT NULL,
    message_type VARCHAR(40) NOT NULL,
    sender_identity_public_key TEXT NOT NULL,
    ephemeral_public_key TEXT,
    ciphertext TEXT NOT NULL,
    nonce TEXT NOT NULL,
    signed_prekey_id INTEGER,
    one_time_prekey_id INTEGER,
    message_index INTEGER,
    ratchet_public_key TEXT,
    previous_chain_length INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, chat_id),
    UNIQUE (chat_id, message_id, target_device_id)
) PARTITION BY HASH (chat_id);

CREATE TABLE message_envelopes_p0 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE message_envelopes_p1 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE message_envelopes_p2 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE message_envelopes_p3 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE message_envelopes_p4 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE message_envelopes_p5 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE message_envelopes_p6 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE message_envelopes_p7 PARTITION OF message_envelopes FOR VALUES WITH (MODULUS 8, REMAINDER 7);

INSERT INTO message_envelopes (
    id, message_id, chat_id, target_user_id, target_device_db_id, target_device_id,
    sender_user_id, sender_device_id, message_type, sender_identity_public_key,
    ephemeral_public_key, ciphertext, nonce, signed_prekey_id, one_time_prekey_id,
    message_index, ratchet_public_key, previous_chain_length, created_at
)
SELECT
    id, message_id, chat_id, target_user_id, target_device_db_id, target_device_id,
    sender_user_id, sender_device_id, message_type, sender_identity_public_key,
    ephemeral_public_key, ciphertext, nonce, signed_prekey_id, one_time_prekey_id,
    message_index, ratchet_public_key, previous_chain_length, created_at
FROM message_envelopes_legacy;

SELECT setval(
    pg_get_serial_sequence('message_envelopes', 'id'),
    COALESCE((SELECT MAX(id) FROM message_envelopes), 1),
    (SELECT MAX(id) FROM message_envelopes) IS NOT NULL
);

DROP TABLE message_envelopes_legacy;

ALTER TABLE message_envelopes
    ADD CONSTRAINT message_envelopes_message_id_fkey
        FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
    ADD CONSTRAINT message_envelopes_target_user_id_fkey
        FOREIGN KEY (target_user_id) REFERENCES users(id),
    ADD CONSTRAINT message_envelopes_target_device_db_id_fkey
        FOREIGN KEY (target_device_db_id) REFERENCES user_devices(id) ON DELETE CASCADE,
    ADD CONSTRAINT message_envelopes_sender_user_id_fkey
        FOREIGN KEY (sender_user_id) REFERENCES users(id),
    ADD CONSTRAINT fk_message_envelopes_chat
        FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE;

CREATE INDEX idx_message_envelopes_message_id ON message_envelopes(message_id);
CREATE INDEX idx_message_envelopes_chat_target_device ON message_envelopes(chat_id, target_device_id);
CREATE INDEX idx_message_envelopes_target_device_db_id ON message_envelopes(target_device_db_id, created_at);
